---
title: "Example Multiple Exposure Fit"
author: "Tom Palmer"
date: "2023-05-18"
format:
  html:
    embed-resources: true
    toc: true
monofont: "Fira Mono"
---

```{=html}
<link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css">
```

```{r include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r message=FALSE}
# library(OneSampleMR)
library(ivreg)
library(gtsummary)
library(dplyr)
library(Statamarkdown)
library(haven)
```

## Simulate data

```{r}
set.seed(9)
n    <- 1000
psi0 <- 0.5
Z1   <- rbinom(n, 1, 0.5)
Z2   <- rbinom(n, 2, .3)
X1   <- rbinom(n, 1, 0.7*Z1 + 0.2*(1 - Z1))
p2   <- 0.1*Z2 + .4*Z1
summary(p2)
X2   <- rbinom(n, 1, p2)
m0   <- plogis(1 + 0.8*X1 - 0.39*Z1)
Y    <- rbinom(n, 1, plogis(psi0*X1 + psi0*X2 + log(m0/(1 - m0))))
dat  <- data.frame(Z1, Z2, X1, X2, Y)
```

```{r}
# fit <- tsps(Y ~ X1 + X2 | Z1 + Z2 , data = dat, link = "logit")
# summary(fit)
```

## Logistic TSPS

```{r}
fitx1     <- lm(X1 ~ Z1 + Z2, data = dat)
dat$x1hat <- fitted.values(fitx1)
dat$x1res <- residuals(fitx1)

fitx2     <- lm(X2 ~ Z1 + Z2, data = dat)
dat$x2hat <- fitted.values(fitx2)
dat$x2res <- residuals(fitx2)

yfit      <- glm(Y ~ x1hat + x2hat, data = dat, family = binomial)
yfit %>% tbl_regression(exp = TRUE)
```

## Linear TSPS 

* TSLS multiple exposures fit

```{r warning=FALSE, message=FALSE}
mvtsls <- ivreg(Y ~ X1 + X2 | Z1 + Z2, data = dat)
mvtsls %>% tbl_regression()
```

* Manual fit

```{r}
yfit2 <- lm(Y ~ x1hat + x2hat, data = dat)
yfit2 %>% tbl_regression()
```

## ivpoisson fit in Stata

```{r}
write_dta(dat, "dat.dta")
```

```{stata collectcode=TRUE, collapse=FALSE}
use dat, clear
ivpoisson cfunction Y (X1 X2 = Z1 Z2), nolog irr
```

* Compare to TSPS Poisson

```{r}
yfit3 <- glm(Y ~ x1hat + x2hat, data = dat, family = poisson)
yfit3 %>% tbl_regression(exp = TRUE)
```

* TSRI Gamma distribution with log link

```{r}
dat <- 
  dat %>%
  mutate(Y1 = case_when(Y == 0 ~ 0.001,
                        Y == 1 ~ 1))
```
```{r}
yfit4 <- glm(Y1 ~ X1 + X2 + x1res + x2res, data = dat, family = Gamma(link = "log"))
yfit4 %>% tbl_regression(exp = TRUE)
```
